name: Frontend CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend   # 👈 THIS IS THE FIX

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 3. Install dependencies
        run: npm install

      - name: 4. Run lint
        run: npm run lint

      - name: 5. Build project
        run: npm run build

      - name: 6. Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: frontend/dist   # 👈 important
      - name: 7. Simulate deployment
        run: |
          mkdir server
          cp -r dist/* server/